services:
  - type: web
    name: agrilive-order-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: RENDER
        value: true
      - key: OPENAI_API_KEY
        sync: false
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
  
  - type: web
    name: line-webhook-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python webhook_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: RENDER
        value: true
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false 