services:
  - type: web
    name: agrilive-order-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: true
      - key: ENV
        value: production
      - key: APP_DATA_DIR
        value: /opt/render/project/src/data
    healthCheckPath: /
    autoDeploy: true 